<?php
/**
 * 单据
 * User: fy
 * Date: 16-7-29
 * Time: 下午2:00
 */

namespace Admin\Controller;


abstract class InvController extends AdminController
{
    protected $account_model;     //  账户

    protected $account_info_model;      //  账户资金流动明细

    protected $invoice_model;     //  单据

    protected $invoice_info_model;    //  单据明细

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        $this->account_model = D('Account');

        $this->account_info_model = D('AccountInfo');

        $this->invoice_model = D('invoice');

        $this->invoice_info_model = D('invoice_info');
    }


    /**
     * 获取单据编号
     */
    public function getBillNo($prefix = '0')
    {
        return C('bill_no_prefix')[$prefix].date('YmdHis').rand(0,9);
    }


    public function getGoods($type = '')
    {
        $modal_title = '请选择商品';

        $model = D('Goods');

        $map = [];
        /*商品类型 成品或半成品*/

        if( !empty($type) ){
            $map['type'] = $type;
        }

        $_list = $this->lists($model, $map);

        foreach ($_list as $key=>&$value) {
            $value['total_qty'] += D('InvoiceInfo')->where(['goods_id'=>$value['id']])->sum('qty');
        }
        
        $goods_category = C('goods_category');

        $unit_list = C('unit_list');

        $goods_storage_house = C('goods_storage_house');

        $this->assign(compact('modal_title', '_list', 'goods_category', 'unit_list', 'goods_storage_house'));

        $this->display('Inv/get_goods');
    }

}