<?php
/**
 * 单据
 * User: fy
 * Date: 16-7-29
 * Time: 下午2:00
 */

namespace Admin\Controller;


abstract class InvController extends AdminController
{
    protected $bill_no_prefix;

    protected $bill_type;

    protected $model_name = 'Invoice';

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 新建 购货单
     */
    public function add()
    {
        $trans_type = I('trans_type', '0');

        if( empty($trans_type) ) {
            $this->error("请求地址,缺少必要参数");
        }

        //  获取采购单据号
        $bill_no = $this->getBillNo( $this->bill_no_prefix );

        $this->assign(compact('trans_type', 'bill_no'));

        // 记录当前列表页的cookie
        Cookie('__forward__',$_SERVER['REQUEST_URI']);

        $this->display();
    }

    /**
     * 保存数据
     */
    public function save()
    {
        $inputs = I('');

        $inputs['inv']['bill_type'] = $this->bill_type;

        $inputs['inv']['__hash__'] = $inputs['__hash__'];
        
        if( !empty( (float)$inputs['inv']['arrears']) ) {
            $this->error( "暂不允许欠款" );
        }

        if( empty($inputs['data']) ) {
            $this->error( "请添加商品信息" );
        }

        if( $this->model->addInvoiceData( $inputs ) ) {
            $this->success($this->model->getErrorMsg(), Cookie('__forward__'), self::AJAX_IS_OPEN);
        }

        $this->error($this->model->getErrorMsg(), '', self::AJAX_IS_OPEN);
    }

    /**
     * 获取单据编号
     */
    public function getBillNo($prefix = '0')
    {
        return C('bill_no_prefix')[$prefix] . date('YmdHis') . rand(0, 9);
    }


    /**
     * 获取商品信息列表
     * @param string $type
     */
    public function getGoods()
    {
        $this->getGoodsList();

        $this->display('Inv/get_goods');
    }

}